// resources/js/app.js
import { createApp } from "vue";
import { createPinia } from "pinia";
import App from "./App.vue";
import router from "./router";
import "../css/app.css";
import { vCan } from "@/directives/can";

// -------------------------------
// CONFIGURACIÓN DE OH-VUE-ICONS
// -------------------------------
import { OhVueIcon, addIcons } from "oh-vue-icons";

import {
  BiPerson,
  BiPeople,
  BiPersonPlus,
  RiMapPinUserLine,
  FaDollarSign,
  OiAlert,
  HiTrendingUp,
  BiActivity,
  RiMapPinLine,
  RiMap2Line,
  RiSettings4Line,
  FaRegularBell,
  IoCalendar,
  HiWifi,
  BiSun,
  BiMoon,
  MdScreenshotmonitor,
  MdLogoutTwotone,
  MdDashboardOutlined,
  BiRouter,
  OiDiffAdded,
  OiPackage,
  RiMoneyDollarCircleLine,
  FaHeadphonesAlt,
  HiBookOpen,
  MdRouterRound,
  MdSupportagentRound,
  HiChevronDown,
  MdChevronleftRound,
  FaArrowLeft,
  FaUserEdit,
  BiHddRack,
  BiSpeedometer2,
  BiWifi,
  BiBroadcastPin,
  BiListTask,
  BiDiagram3,
  BiHddNetwork,
  BiServer,
  RiListSettingsLine,
  BiPeopleFill,
  FaFileInvoiceDollar,
  RiAdminFill,
  BiHeadset,
  HiChevronRight,
  HiLightBulb,
  IoClose,
  HiTicket,
  LaMoneyBillWaveSolid,
  BiPaperclip,
  IoSearch,
  BiFileEarmark,
  BiArrowRepeat,
  MdArrowback,
  BiBoxSeam,
  MdAdd,
  LaDollarSignSolid,
  MdPendingTwotone,
  MdWarningRound,
  MdTrendingupRound,
  MdSearch,
  BiFilter,
  BiCalendar,
  LaFileInvoiceDollarSolid,
  MdSave,
  MdPalette,
  MdComputer,
  MdInfo,
  MdLanguage,
  MdKeyboardarrowdown,
  MdLightmode,
  MdNightlight,
  MdBrush,
  MdTextfields,
  MdAnimation,
  MdEmail,
  BiBell,
  MdWarning,
  MdBuild,
  MdDelete,
  BiImages,
  FaEdit,
  FaEye,
  FaEyeSlash,
  RiArrowGoBackLine,
  MdDownload,
  MdChevronright,
  BiCheckCircleFill,
  MdError,
  MdSchedule,
  MdPaymentsOutlined,
  MdFiledownload,
  MdPrint,
  MdShare,
  MdTrendingdown,
  MdRouter,
  MdWifi,
  MdPerson,
  MdLock,
  MdLocationon,
  MdDescription,
  MdEdit,
  MdClose,
  MdFilterlist,
  MdAdminpanelsettingsRound,
  MdPublicRound,
  MdSecurityRound,
  FaWhatsapp,
  MdWarningamberRound,
  MdInventoryRound,
  BiBuilding,
  MdStoremalldirectory,
  BiUpc,
  MdVisibility,
  MdCheck,
  MdNotifications,
  MdCloudupload,
  MdUploadfile,
  MdHelpOutlined,
  ViFileTypeExcel,
  RiLoader4Line,
  MdList,
  MdCheckcircle,
  MdNotificationsactiveOutlined,
  MdSend,
  RiBillLine,
  RiBankCardLine,
  MdPausecircle,
  MdPlaycircle,
  MdDeleteforever,
  BiCalendarCheck,
  HiChevronLeft,
  BiPlusCircle,
  MdSettings,
} from "oh-vue-icons/icons";

// REGISTRAR ICONOS
addIcons(
  BiPerson,
  BiPeople,
  BiPersonPlus,
  RiMapPinUserLine,
  FaDollarSign,
  OiAlert,
  HiTrendingUp,
  BiActivity,
  RiMapPinLine,
  RiMap2Line,
  RiSettings4Line,
  FaUserEdit,
  FaRegularBell,
  IoCalendar,
  HiWifi,
  BiSun,
  BiMoon,
  MdScreenshotmonitor,
  MdLogoutTwotone,
  MdDashboardOutlined,
  BiRouter,
  BiListTask,
  BiWifi,
  BiDiagram3,
  BiHddNetwork,
  BiServer,
  OiDiffAdded,
  OiPackage,
  RiMoneyDollarCircleLine,
  FaHeadphonesAlt,
  HiBookOpen,
  MdRouterRound,
  MdSupportagentRound,
  HiChevronDown,
  MdChevronleftRound,
  FaArrowLeft,
  BiHddRack,
  BiSpeedometer2,
  BiBroadcastPin,
  RiListSettingsLine,
  BiPeopleFill,
  FaFileInvoiceDollar,
  RiAdminFill,
  BiHeadset,
  HiChevronRight,
  HiLightBulb,
  IoClose,
  HiTicket,
  LaMoneyBillWaveSolid,
  BiPaperclip,
  IoSearch,
  BiFileEarmark,
  BiArrowRepeat,
  MdArrowback,
  BiBoxSeam,
  MdAdd,
  LaDollarSignSolid,
  MdPendingTwotone,
  MdWarningRound,
  MdTrendingupRound,
  MdSearch,
  BiFilter,
  BiCalendar,
  LaFileInvoiceDollarSolid,
  MdPalette,
  MdInfo,
  MdLanguage,
  MdSave,
  MdKeyboardarrowdown,
  MdLightmode,
  MdNightlight,
  MdComputer,
  MdBrush,
  MdTextfields,
  MdAnimation,
  MdEmail,
  BiBell,
  MdWarning,
  MdBuild,
  MdDelete,
  BiImages,
  FaEdit,
  FaEye,
  FaEyeSlash,
  RiArrowGoBackLine,
  MdDownload,
  MdChevronright,
  BiCheckCircleFill,
  MdError,
  MdSchedule,
  MdPaymentsOutlined,
  MdFiledownload,
  MdPrint,
  MdShare,
  MdTrendingdown,
  MdRouter,
  MdWifi,
  MdPerson,
  MdLock,
  MdLocationon,
  MdDescription,
  MdEdit,
  MdClose,
  MdFilterlist,
  MdAdminpanelsettingsRound,
  MdPublicRound,
  MdSecurityRound,
  FaWhatsapp,
  MdWarningamberRound,
  MdInventoryRound,
  BiBuilding,
  MdStoremalldirectory,
  BiUpc,
  MdVisibility,
  MdCheck,
  MdNotifications,
  MdCloudupload,
  MdUploadfile,
  MdHelpOutlined,
  ViFileTypeExcel,
  RiLoader4Line,
  MdList,
  MdCheckcircle,
  MdNotificationsactiveOutlined,
  MdSend,
  RiBillLine,
  RiBankCardLine,
  MdPausecircle,
  MdPlaycircle,
  MdDeleteforever,
  BiCalendarCheck,
  HiChevronLeft,
  BiPlusCircle,
  MdSettings,
);

// -------------------------------
// CREACIÓN DE LA APP
// -------------------------------
const pinia = createPinia();
const app = createApp(App);

// Pinia state management (MUST be registered before router)
app.use(pinia);

// Register OhVueIcon component
app.component("v-icon", OhVueIcon);

// Router
app.use(router);

// Global custom directives
app.directive('can', vCan);

// Mount
app.mount("#app");
